clean: true
output: docs
theme: fullwidth
objc: true
sdk: iphonesimulator
module: TypeStatus
umbrella_header: api/TypeStatusProvider.h
framework_root: .theos/_/usr/lib
author: HASHBANG Productions
author_url: https://hbang.github.io/
github_url: https://github.com/hbang/TypeStatus
root_url: https://hbang.github.io/TypeStatus/
dash_url: https://hbang.github.io/TypeStatus/docsets/TypeStatus.xml
readme: README.md
# documentation: info/*.md
exclude: "*/include/*"
hide_documentation_coverage: true
